### ISSUE TITLE
'BidirectionalIterator' is deprecated

### ISSUE THREAD

**Issue by MELICI0US** [appsup-dart/sortedmap#5]
This class is used in the treeset.dart file. It will be removed in an upcoming release, and is already removed on the master channel. Replacing it soon would be a good idea.

**Comment by rbellens** [comment]
@MELICI0US thanks for pointing this out. I will fix it soon.

**Comment by venky9885** [comment]
Same issue undergoing please fix it ASAp

Pub/Cache/hosted/pub.dev/sortedmap-0.5.2/lib/src/treeset.dart(18,3): error G5FE39F1E: Type 'BidirectionalIterator' not found. [D:\Flutter projects\Dop_Software_Code_New_Old\DESKTOP\soft_desk\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by yahu1031** [comment]
`Type 'BidirectionalIterator' not found.` @rbellens Fix ASAP.

**Comment by rbellens** [comment]
this is now fixed
